### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by ProcsWS** [Machibuse/BananaBarClassic#1]
) "Hide unused buttons" doesnt work
) disable "Show buttons in party" does nothing
) disable "Show buttons in raid" also disables the buttons in the raid and in the group
) if 2 different and unmarked mobs are targeted (and/or mouseover) u will get chatspammed like this:
![image](https://user-images.githubusercontent.com/20246220/78999266-8eb14500-7b4a-11ea-8f83-9f2072ce3af2.png)

**Comment by Machibuse** [comment]
Should be solved in the meantime.
