### ISSUE TITLE
inspiration from weakaura

### ISSUE THREAD

**Issue by FelixRTU** [Machibuse/BananaBarClassic#2]
Hey, I found a weak aura a while ago with the same goal as you. It basically has the functionality **but** you can target the enemies by clicking on the icons. Which is my main reason for using it. you may wanna look into it. Nice work so far :) 

here is the link: https://wago.io/4DFYe3Qfb

**Comment by Machibuse** [comment]
i have taken a look, it only works if the partymember, targeting a mob with a specific symbol dont changes his target after getting in combat
