### ISSUE TITLE
[lua errors]

### ISSUE THREAD

**Issue by waytoomuchgaming** [Machibuse/BananaBarClassic#3]
These 4 bugs come at every login:

1x AceLocale-3.0-6: BananaBar2: Missing entry for 'autosetcombat'
BananaBarClassic\BananaBar2-2.0.107.nil.lua:79: in main chunk

---

1x AceLocale-3.0-6: BananaBar2: Missing entry for 'autosetcombatdesc'
BananaBarClassic\BananaBar2-2.0.107.nil.lua:80: in main chunk

---

1x AceLocale-3.0-6: BananaBar2: Missing entry for 'unmarked'
BananaBarClassic\BananaBar2-2.0.107.nil.lua:427: in main chunk

---

1x AceLocale-3.0-6: BananaBar2: Missing entry for 'showunmarkeddesc'
BananaBarClassic\BananaBar2-2.0.107.nil.lua:428: in main chunk

**Comment by Machibuse** [comment]
was missing translations, sould be solved
